replicaCount: 1

image:
  repository: facundo676/backend-shop
  tag: "20251219-042907-82ab468"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512i
  requests:
    cpu: 200m
    memory: 256Mi

env:
  SPRING_PROFILES_ACTIVE: "demo" #se puede poner dev pero necesita mysql
  SERVER_PORT: "8080"